repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

#   - repo: https://github.com/pycqa/flake8
#     rev: 7.2.0
#     hooks:
#       - id: flake8
#         additional_dependencies: ["flake8-pyproject"]
#         args: ['--ignore=E731,E701']
#         exclude: samplers/samplers

#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.15.0
#     hooks:
#       - id: mypy
#         args: ["--ignore-missing-imports"]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        language_version: python3.12
